package com.google.android.gms.internal;

import android.support.annotation.NonNull;
import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.TransformedResult;
import java.util.concurrent.TimeUnit;

public final class zzbec<R extends Result> extends OptionalPendingResult<R> {
    private final zzbbe<R> zzaEQ;

    public zzbec(PendingResult<R> pendingResult) {
        if (pendingResult instanceof zzbbe) {
            this.zzaEQ = (zzbbe) pendingResult;
            return;
        }
        throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }

    public final R await() {
        return this.zzaEQ.await();
    }

    public final R await(long j, TimeUnit timeUnit) {
        return this.zzaEQ.await(j, timeUnit);
    }

    public final void cancel() {
        this.zzaEQ.cancel();
    }

    public final R get() {
        if (isDone()) {
            return await(0, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    public final boolean isCanceled() {
        return this.zzaEQ.isCanceled();
    }

    public final boolean isDone() {
        return this.zzaEQ.isReady();
    }

    public final void setResultCallback(ResultCallback<? super R> resultCallback) {
        this.zzaEQ.setResultCallback(resultCallback);
    }

    public final void setResultCallback(ResultCallback<? super R> resultCallback, long j, TimeUnit timeUnit) {
        this.zzaEQ.setResultCallback(resultCallback, j, timeUnit);
    }

    @NonNull
    public final <S extends Result> TransformedResult<S> then(@NonNull ResultTransform<? super R, ? extends S> resultTransform) {
        return this.zzaEQ.then(resultTransform);
    }

    public final void zza(zza com_google_android_gms_common_api_PendingResult_zza) {
        this.zzaEQ.zza(com_google_android_gms_common_api_PendingResult_zza);
    }

    public final Integer zzpo() {
        return this.zzaEQ.zzpo();
    }
}
