package com.google.android.gms.internal;

import android.support.annotation.NonNull;
import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.TransformedResult;
import java.util.concurrent.TimeUnit;

public final class zzbec<R extends Result>
  extends OptionalPendingResult<R>
{
  private final zzbbe<R> zzaEQ;
  
  public zzbec(PendingResult<R> paramPendingResult)
  {
    if (!(paramPendingResult instanceof zzbbe)) {
      throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }
    this.zzaEQ = ((zzbbe)paramPendingResult);
  }
  
  public final R await()
  {
    return this.zzaEQ.await();
  }
  
  public final R await(long paramLong, TimeUnit paramTimeUnit)
  {
    return this.zzaEQ.await(paramLong, paramTimeUnit);
  }
  
  public final void cancel()
  {
    this.zzaEQ.cancel();
  }
  
  public final R get()
  {
    if (isDone()) {
      return await(0L, TimeUnit.MILLISECONDS);
    }
    throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
  }
  
  public final boolean isCanceled()
  {
    return this.zzaEQ.isCanceled();
  }
  
  public final boolean isDone()
  {
    return this.zzaEQ.isReady();
  }
  
  public final void setResultCallback(ResultCallback<? super R> paramResultCallback)
  {
    this.zzaEQ.setResultCallback(paramResultCallback);
  }
  
  public final void setResultCallback(ResultCallback<? super R> paramResultCallback, long paramLong, TimeUnit paramTimeUnit)
  {
    this.zzaEQ.setResultCallback(paramResultCallback, paramLong, paramTimeUnit);
  }
  
  @NonNull
  public final <S extends Result> TransformedResult<S> then(@NonNull ResultTransform<? super R, ? extends S> paramResultTransform)
  {
    return this.zzaEQ.then(paramResultTransform);
  }
  
  public final void zza(PendingResult.zza paramzza)
  {
    this.zzaEQ.zza(paramzza);
  }
  
  public final Integer zzpo()
  {
    return this.zzaEQ.zzpo();
  }
}


/* Location:              /home/fabian/Escritorio/Proyectos/Android/Dev/jardecompiler/TMessagesProj-fat-debug.jar!/com/google/android/gms/internal/zzbec.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1-SNAPSHOT-20140817
 */