package com.google.android.gms.internal;

import android.support.annotation.NonNull;
import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.TransformedResult;
import java.util.concurrent.TimeUnit;

public final class zzrg<R extends Result> extends OptionalPendingResult<R> {
    private final zzqe<R> zi;

    public zzrg(PendingResult<R> pendingResult) {
        if (pendingResult instanceof zzqe) {
            this.zi = (zzqe) pendingResult;
            return;
        }
        throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }

    public R await() {
        return this.zi.await();
    }

    public R await(long j, TimeUnit timeUnit) {
        return this.zi.await(j, timeUnit);
    }

    public void cancel() {
        this.zi.cancel();
    }

    public R get() {
        if (isDone()) {
            return await(0, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    public boolean isCanceled() {
        return this.zi.isCanceled();
    }

    public boolean isDone() {
        return this.zi.isReady();
    }

    public void setResultCallback(ResultCallback<? super R> resultCallback) {
        this.zi.setResultCallback(resultCallback);
    }

    public void setResultCallback(ResultCallback<? super R> resultCallback, long j, TimeUnit timeUnit) {
        this.zi.setResultCallback(resultCallback, j, timeUnit);
    }

    @NonNull
    public <S extends Result> TransformedResult<S> then(@NonNull ResultTransform<? super R, ? extends S> resultTransform) {
        return this.zi.then(resultTransform);
    }

    public void zza(zza com_google_android_gms_common_api_PendingResult_zza) {
        this.zi.zza(com_google_android_gms_common_api_PendingResult_zza);
    }

    public Integer zzaqf() {
        return this.zi.zzaqf();
    }
}
