package com.google.android.gms.internal;

import android.support.annotation.NonNull;
import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.TransformedResult;
import java.util.concurrent.TimeUnit;

public final class zzru<R extends Result> extends OptionalPendingResult<R> {
    private final zzqq<R> Bp;

    public zzru(PendingResult<R> pendingResult) {
        if (pendingResult instanceof zzqq) {
            this.Bp = (zzqq) pendingResult;
            return;
        }
        throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }

    public R await() {
        return this.Bp.await();
    }

    public R await(long j, TimeUnit timeUnit) {
        return this.Bp.await(j, timeUnit);
    }

    public void cancel() {
        this.Bp.cancel();
    }

    public R get() {
        if (isDone()) {
            return await(0, TimeUnit.MILLISECONDS);
        }
        throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
    }

    public boolean isCanceled() {
        return this.Bp.isCanceled();
    }

    public boolean isDone() {
        return this.Bp.isReady();
    }

    public void setResultCallback(ResultCallback<? super R> resultCallback) {
        this.Bp.setResultCallback(resultCallback);
    }

    public void setResultCallback(ResultCallback<? super R> resultCallback, long j, TimeUnit timeUnit) {
        this.Bp.setResultCallback(resultCallback, j, timeUnit);
    }

    @NonNull
    public <S extends Result> TransformedResult<S> then(@NonNull ResultTransform<? super R, ? extends S> resultTransform) {
        return this.Bp.then(resultTransform);
    }

    public void zza(zza com_google_android_gms_common_api_PendingResult_zza) {
        this.Bp.zza(com_google_android_gms_common_api_PendingResult_zza);
    }

    public Integer zzarh() {
        return this.Bp.zzarh();
    }
}
